name: MATLAB lint

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/scripts/**"
      - ".github/workflows/matlab-lint.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/scripts/**"
      - ".github/workflows/matlab-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run MATLAB Code Analyzer
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('.github/scripts'); lint

      - name: Upload lint log (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-lint-log
          path: .github/scripts/lint.log
          if-no-files-found: ignore
